# Generated by Django 6.0.1 on 2026-01-22 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('current_status', models.CharField(choices=[('student', 'Student'), ('college_student', 'College Student'), ('working_professional', 'Working Professional')], default='student', max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('highest_qualification', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(blank=True, max_length=150)),
                ('field_of_study', models.CharField(blank=True, max_length=100)),
                ('current_year', models.CharField(blank=True, max_length=50)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('career_interests', models.TextField(blank=True, help_text='Comma-separated career interests')),
                ('subject_interests', models.TextField(blank=True, help_text='Comma-separated subject interests')),
                ('preferred_work_type', models.CharField(blank=True, choices=[('office', 'Office'), ('remote', 'Remote'), ('field', 'Field')], default='office', max_length=20)),
                ('preferred_locations', models.TextField(blank=True, help_text='Comma-separated preferred locations')),
                ('salary_expectation', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='techbrat.userprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='techbrat.userprofile')),
            ],
            options={
                'ordering': ['skill_name'],
                'unique_together': {('profile', 'skill_name')},
            },
        ),
    ]
