# Generated by Django 6.0.1 on 2026-02-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbrat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='career_interests',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_year',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='highest_qualification',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_locations',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_work_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='salary_expectation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subject_interests',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career_objective',
            field=models.CharField(choices=[('job', 'Job'), ('startup', 'Startup'), ('freelancing', 'Freelancing'), ('higher_studies', 'Higher Studies')], default='job', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_course',
            field=models.CharField(blank=True, help_text='e.g., B.Tech in Computer Science', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(choices=[('school', 'School (K-12)'), ('intermediate', 'Intermediate (10+2)'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('doctorate', 'Doctorate')], default='undergraduate', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_domain_work_type',
            field=models.CharField(choices=[('development', 'Development'), ('analytical', 'Analytical'), ('research', 'Research'), ('creative_ui', 'Creative UI'), ('security', 'Security')], default='development', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_work_mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('on_site', 'On-site'), ('hybrid', 'Hybrid')], default='remote', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_timeline',
            field=models.CharField(blank=True, help_text='e.g., Within 6 months', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tech_domains',
            field=models.TextField(blank=True, help_text='Comma-separated tech domains (AI/ML, Web Dev, etc.)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_of_study',
            field=models.CharField(blank=True, help_text='e.g., 3rd Year', max_length=50),
        ),
    ]
