# Generated by Django 6.0.1 on 2026-02-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techbrat', '0002_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExperience',
        ),
    ]
