# Generated by Django 6.0.1 on 2026-02-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbrat', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_type',
            field=models.CharField(choices=[('video', 'Video Based'), ('text', 'Text Based'), ('interactive', 'Interactive Coding'), ('project', 'Project Based')], default='video', max_length=20),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level'], name='techbrat_co_level_a3390a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['domain'], name='techbrat_co_domain_19cc58_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['learning_type'], name='techbrat_co_learnin_32357e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_free'], name='techbrat_co_is_free_aa8502_idx'),
        ),
    ]
