# Generated by Django 6.0.1 on 2026-04-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbrat', '0005_course_is_ai_generated_course_learning_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
