# Generated by Django 6.0.1 on 2026-04-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbrat', '0007_merge_conflict_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('development', 'Development'), ('version_control', 'Version Control'), ('practice_platform', 'Practice Platform'), ('design', 'Design'), ('devops', 'DevOps'), ('ai_tools', 'AI Tools'), ('databases', 'Databases'), ('api_tools', 'API Tools'), ('cloud', 'Cloud Platform'), ('ci_cd', 'CI/CD'), ('collaboration', 'Collaboration'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('use_case', models.CharField(choices=[('learning', 'Learning'), ('practice', 'Practice'), ('production', 'Production'), ('all', 'All')], default='all', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All Levels')], default='all', max_length=20)),
                ('link', models.URLField()),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='techbrat_bo_level_7bff92_idx',
            old_name='techbrat_bo_level_2c0f49_idx',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='techbrat_bo_domain_aa6985_idx',
            old_name='techbrat_bo_domain_4707e6_idx',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='techbrat_bo_book_ty_1b14d0_idx',
            old_name='techbrat_bo_book_ty_02f762_idx',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='techbrat_bo_is_ai_g_0636b5_idx',
            old_name='techbrat_bo_is_ai_g_f68d9a_idx',
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['category'], name='techbrat_to_categor_173ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['difficulty'], name='techbrat_to_difficu_cef71f_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['use_case'], name='techbrat_to_use_cas_46f15a_idx'),
        ),
        migrations.AddIndex(
            model_name='tool',
            index=models.Index(fields=['is_ai_generated'], name='techbrat_to_is_ai_g_d4020d_idx'),
        ),
    ]
