# Generated by Django 6.0.1 on 2026-04-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbrat', '0008_tool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('action_step', models.TextField()),
                ('category', models.CharField(choices=[('productivity', 'Productivity'), ('learning_strategy', 'Learning Strategy'), ('coding_practice', 'Coding Practice'), ('career_growth', 'Career Growth'), ('consistency', 'Consistency'), ('mindset', 'Mindset')], default='productivity', max_length=50)),
                ('icon', models.CharField(default='fa-lightbulb', help_text='Font Awesome icon class', max_length=50)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('daily_boost', models.BooleanField(default=False, help_text='Show in hero section as daily motivation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='techbrat_ti_categor_3cd6e4_idx'), models.Index(fields=['is_ai_generated'], name='techbrat_ti_is_ai_g_35d2d5_idx'), models.Index(fields=['daily_boost'], name='techbrat_ti_daily_b_2e4f7a_idx')],
            },
        ),
    ]
