# Generated by Django 6.0.1 on 2026-04-04 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbrat', '0012_companyprepsnapshot_issueassistancesnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='techbrat.roadmapsnapshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_step_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['step_index'],
                'indexes': [models.Index(fields=['user', 'snapshot'], name='techbrat_ro_user_id_043b4e_idx'), models.Index(fields=['completed_at'], name='techbrat_ro_complet_8fbcef_idx')],
                'unique_together': {('user', 'snapshot', 'step_index')},
            },
        ),
    ]
